chatMessenger/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import security
import dashboard

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('security.urls', namespace='auth')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
]

security/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.do_logout, name='logout'),
]

common/forms.py
from django import forms
from security.models import ChatUser

class LoginForm(forms.Form):
    username = forms.CharField(label="Username",
                               widget=forms.TextInput(attrs={'placeholder': 'enter username here',
                                                             'class': 'keep-right'}))
    password = forms.CharField(label="Password",
                               widget=forms.PasswordInput(attrs={'placeholder': 'password',
                                                                 'class': 'keep-right'}))

    class Meta:
        fields = ('username', 'password')


class SignupForm(forms.ModelForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'placeholder': 'Enter username for login',
                                                             'class': 'keep-right'}))
    first_name = forms.CharField(label='First name',
                               widget=forms.TextInput(attrs={'placeholder': 'First name',
                                                             'class': 'keep-right'}))
    last_name = forms.CharField(label='Last name',
                               widget=forms.TextInput(attrs={'placeholder': 'Last name',
                                                             'class': 'keep-right'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'keep-right'}))
    password2 = forms.CharField(label='Confirm password',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter password',
                                                                  'class': 'keep-right'}))

    class Meta:
        model = ChatUser
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            self.add_error("password2", "Password don't match")

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        return user

common/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_tags %}
<html lang="en">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Chat Messenger" />

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src='{% static "js/control.utils.js" %}'></script>
    <script src='{% static "js/js.cookie.js" %}'></script>
    <link rel='shortcut icon' type='image/x-icon' href="/static/images/favicon.jpeg" />
    <link rel='stylesheet' type='text/css', href='{% static "css/bootstrap.custom.3.3.1.min.css" %}' />

{% block title %}
        <title>Chat Messenger</title>
{% endblock %}
</head>
<body>
    <div class="header-wrapper">
        <div class="header">
            <div class="logo">
                <span class="chat">Chat </span><span class="messenger">messenger...</span>
            </div>
        </div>
    </div>
    <nav  class="dropdown navbar navbar-inverse navbar-header-full navbar-dark yamm navbar-static-top" role="navigation" >
        <div class="container">
            <div class="collapse navbar-collapse" id="navi">
                <ul class="nav navbar-nav">
                      {% if request.user.is_active %}
                        <li><a href="/">ChatMess</a></li>

                        <li><a href="/">About</a></li>
                        <li><a href="/">Licence</a></li>
                      {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_active %}
                    <li><p class="welcome">Welcome : {{ request|getuser }} </p></li>
                    <li><a href="{% url 'auth:logout' %}"><span class="glyphicon glyphicon-log-out">Logout</span></a></li>
                    {% else %}
                    <li><a href="{% url 'auth:signup' %}"><span class="glyphicon glyphicon-user">SignUp</span></a></li>
                    <li><a href="{% url 'auth:login' %}"><span class="glyphicon glyphicon-log-in">Login</span></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block body_block %}
    <div>Body block for chat messenger</div>
    {% endblock %}
    <script src='{% static "js/control.js" %}'></script>
</body>
</html>

common/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
        <div class="row" style="margin-top: -20px;">
            <div class="col-xs-12">
                <div class="panel panel-default">
                    <div class="form-small centred">
                        {% if data.error %}
                            {% block error_block %}
                                <p class="error-login">......... {{ data.error }}</p>
                                <a href="{% url 'auth:login' %}" style="margin-left: 280px;">Try again...</a>
                            {% endblock %}
                        {% else %}
                            <div class="form-login centred">
                                <form method="post" action="{{ target }}">
                                    {% csrf_token %}
                                        <table class="login-form">
                                            {% for field in form %}
                                                <tr>
                                                    <td align="right">{{ field.label_tag }}</td>
                                                    <td align="right">{{ field }}</td>
                                                </tr>
                                            {% endfor %}
                                            <input type="hidden" name="next" value="{{ next }}" />
                                        </table>
                                    <button type="submit" class="login-button" value="{{ button_text }}">{{ button_text }}</button>
                                </form>
                                <p class="signup">New user <a href="{% url 'auth:signup' %}">sign up</a></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

common/templates/signup.html
{% extends 'base.html' %}

{% block title %}
        <title>Task user sign up</title>
{% endblock %}

{% block body_block %}
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="form centred">
                    {% if data.status %}
                        {% block status_block %}
                             <p class="signup-success">{{ data.status }}</p>
                            <p style="margin-left: 280px;">click to <a href="{{ next }}">continue</a>
                         {% endblock %}
                    {% else %}
                        <div class="form centred">
                            <form method="post" action="{{ target }}">
                                {% csrf_token %}
                                <table class="form-large">
                                    {% for field in form %}
                                     {% if field.errors %}
                                            {% for error in field.errors %}
                                                <tr class="error-row"><td></td><td><p class="errorlist keep-right">*{{ error }}</p></div></tr>
                                            {% endfor %}
                                        {% endif %}
                                    <tr style="height:40px;">

                                        <td align="right">{{ field.label_tag }}</td><td align="left">{{ field }}</td>
                                    </tr>
                                    {% endfor %}
                                 </table>
                                <button type="submit" value="{{ button_text }}" class="form-bottom-center signup-button">{{ button_text }}</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}